name: LateX CV to PDF
on:
  push:
    branches: 
      - main
  pull_request:
    branches: [ main ]

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2
      - name: latex2pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.1.0
        with:
          output_dir: download
          main_latex_file: main.tex
      - name: push
        uses: actions-x/commit@v6
