name: LateX CV to PDF
on:
  push:
    branches: 
      - main
  pull_request:
    branches: [ main ]

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile cv to pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.1.0
        with:
          output_dir: download
          main_latex_file: mai-joel_maximilian-curriculum_vitae.tex
          ctan_packages: ifmtarg xstring xifthen raleway fontenc moresize fontawesome paracol geometry fancyhdr array graphicx tikz transparent color hidelinks
      - name: Push pdf to repository
        uses: actions-x/commit@v6
